// Dados dos credores fixos mensais - Prefeitura Municipal de Inajá
// Gerado automaticamente a partir do arquivo CREDORES_mes2_destacado.xlsx
// Para atualizar, execute: python exportar_dados.py

const CREDORES_FIXOS = [
  {
    "id": 1,
    "NOME": "EMPASOFT",
    "VALOR": 799.99,
    "DESCRIÇÃO": "LINHA TELEFÔNICA",
    "CNPJ": "03.404.680/0001-05",
    "EMAIL": "G21@G21TELECOM.COM.BR",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": "VENCIDO"
  },
  {
    "id": 2,
    "NOME": "L. RICARDO DE MAGALHAES",
    "VALOR": 1489.82,
    "DESCRIÇÃO": "SOFTWARE PARA LICITAÇÃO",
    "CNPJ": "17.922.286/0001-65",
    "EMAIL": "financeiro@sistematrazvalor.com.br",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 3,
    "NOME": "LF SISTEMAS",
    "VALOR": 1700.00,
    "DESCRIÇÃO": "SOFTWARE PARA LICITAÇÃO",
    "CNPJ": "46.777.506/0001-02",
    "EMAIL": "orcamento@sistemaslf.com.br",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 4,
    "NOME": "J SILVA",
    "VALOR": 2143.50,
    "DESCRIÇÃO": "RADIALISTA",
    "CNPJ": "",
    "EMAIL": "",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 5,
    "NOME": "ANTELMO",
    "VALOR": 2300.00,
    "DESCRIÇÃO": "AULAS DE CAPOEIRA",
    "CNPJ": "17.591.235/0001-06",
    "EMAIL": "gilmadureira@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "1",
    "PAGAMENTO": "5",
    "DEPARTAMENTO": "EDUCAÇÃO",
    "OBS": ""
  },
  {
    "id": 6,
    "NOME": "D. SORTI & SORTI LTDA - ME",
    "VALOR": 2650.00,
    "DESCRIÇÃO": "LIXO HOSPITALAR",
    "CNPJ": "00.173.763/0001-34",
    "EMAIL": "danielsorti@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "SAÚDE",
    "OBS": ""
  },
  {
    "id": 7,
    "NOME": "VERA LUCIA FERREIRA",
    "VALOR": 2813.81,
    "DESCRIÇÃO": "OFICINA DE ARTESANATO",
    "CNPJ": "60.578.488/0001-60",
    "EMAIL": "MEDEIROS_VERALUCIA80@GMAIL.COM",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 8,
    "NOME": "KESIA APARECIDA",
    "VALOR": 3030.00,
    "DESCRIÇÃO": "ORIENTADORA SOCIAL",
    "CNPJ": "43.031.315/0001-09",
    "EMAIL": "kesiapsicologia@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 9,
    "NOME": "MARCOS ANDRE RIBEIRO",
    "VALOR": 3770.00,
    "DESCRIÇÃO": "FOTOGRAFIA DE EVENTOS E DEMAIS",
    "CNPJ": "28.051.421/0001-60",
    "EMAIL": "MARCOS.ANDRE.UNIPAR@GMAIL.COM",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 10,
    "NOME": "G FOUR",
    "VALOR": 4215.00,
    "DESCRIÇÃO": "INTERNET",
    "CNPJ": "10.192.962/0001-43",
    "EMAIL": "ap-bruzaroschi@bol.com.br",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 11,
    "NOME": "GABRIEL GOUVEIA DE OLIVEIRA",
    "VALOR": 4467.49,
    "DESCRIÇÃO": "ADVOGADO",
    "CNPJ": "",
    "EMAIL": "",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 12,
    "NOME": "PRODASP",
    "VALOR": 4537.01,
    "DESCRIÇÃO": "REFERENTE A CÂMARA MUNICIPAL",
    "CNPJ": "84.785.070/0001-92",
    "EMAIL": "miihrosada@gmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 13,
    "NOME": "OPPORTUNITY",
    "VALOR": 4850.00,
    "DESCRIÇÃO": "ASSESSORIA",
    "CNPJ": "11.063.183/0001-00",
    "EMAIL": "OPPORTUNITYASSESSORIA2014@GMAIL.COM",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 14,
    "NOME": "MUNICIPIO PARANAVAI",
    "VALOR": 5740.57,
    "DESCRIÇÃO": "USO DO ATERRO",
    "CNPJ": "76.977.768/0001-81",
    "EMAIL": "",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 15,
    "NOME": "DEL GROSSI",
    "VALOR": 5960.00,
    "DESCRIÇÃO": "JORNAL",
    "CNPJ": "79.989.505/0001-80",
    "EMAIL": "rauldelgrossi@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 16,
    "NOME": "MARLENE OLIVEIRA",
    "VALOR": 6060.00,
    "DESCRIÇÃO": "LOCAÇÃO DAS IMPRESSORAS",
    "CNPJ": "30.502.537/0001-10",
    "EMAIL": "marlenemoretto@outlook.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 17,
    "NOME": "ROSIANE OLIVEIRA LIMA GONÇALVES EIRELI",
    "VALOR": 5690.00,
    "DESCRIÇÃO": "ASSESSORIA",
    "CNPJ": "22.762.257/0001-13",
    "EMAIL": "DIGITALGRC@GMAIL.COM",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 18,
    "NOME": "PRISMA",
    "VALOR": 10000.00,
    "DESCRIÇÃO": "ASSESSORIA",
    "CNPJ": "",
    "EMAIL": "ANISIO@ALVORADAESCRITORIO.COM.BR",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 19,
    "NOME": "AVR",
    "VALOR": 10000.00,
    "DESCRIÇÃO": "ADOLFO",
    "CNPJ": "",
    "EMAIL": "ALVORADA@ALVORADAESCRITORIO.COM.BR",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 20,
    "NOME": "PRODASP",
    "VALOR": 21072.82,
    "DESCRIÇÃO": "REFERENTE A PREFEITURA MUNICIPAL",
    "CNPJ": "84.785.070/0001-92",
    "EMAIL": "miihrosada@gmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  },
  {
    "id": 21,
    "NOME": "RENATA DA SILVA",
    "VALOR": 2232.60,
    "DESCRIÇÃO": "OFICINA DE ESPORTE E LAZER",
    "CNPJ": "40.218.309/0001-77",
    "EMAIL": "wvjtreinamentoepilates@gmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 22,
    "NOME": "E R BOSSOLANI",
    "VALOR": 2440.00,
    "DESCRIÇÃO": "OFICINA DE MÚSICA",
    "CNPJ": "32.369.679/0001-87",
    "EMAIL": "erbsom.eventos@gmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 23,
    "NOME": "EDSON TADAYUKI",
    "VALOR": 2476.95,
    "DESCRIÇÃO": "OFICINA DE DEFESA PESSOAL",
    "CNPJ": "43.133.353/0001-72",
    "EMAIL": "escritorio_elite@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 24,
    "NOME": "CAMILA RODRIGUES",
    "VALOR": 2167.00,
    "DESCRIÇÃO": "OFICINA DE YOGA",
    "CNPJ": "07.910.317/0001-04",
    "EMAIL": "pirescontabil@hotmail.com",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "5",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "ASSISTÊNCIA SOCIAL",
    "OBS": ""
  },
  {
    "id": 25,
    "NOME": "LUCIO FERNANDES ENARES",
    "VALOR": 0,
    "DESCRIÇÃO": "ATENDIMENTOS MÉDICOS EM GERAL",
    "CNPJ": "40.064.403/0001-19",
    "EMAIL": "dr.lucio.enares@gmail.com",
    "TIPO DE VALOR": "VARIÁVEL",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "10",
    "DEPARTAMENTO": "SAÚDE",
    "OBS": ""
  },
  {
    "id": 26,
    "NOME": "SAMUEL CERQUEIRA",
    "VALOR": 0,
    "DESCRIÇÃO": "FANFARRA",
    "CNPJ": "32.757.814/0001-61",
    "EMAIL": "SAMUEL.CERQUEIRA.91@OUTLOOK.COM.BR",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "15",
    "PAGAMENTO": "20",
    "DEPARTAMENTO": "EDUCAÇÃO",
    "OBS": ""
  },
  {
    "id": 27,
    "NOME": "INSTAR TECNOLOGIA",
    "VALOR": 0,
    "DESCRIÇÃO": "HOSPEDAGEM DO SITE",
    "CNPJ": "",
    "EMAIL": "JURIDICO@INSTAR.COM.BR",
    "TIPO DE VALOR": "FIXO",
    "SOLICITAÇÃO": "",
    "PAGAMENTO": "",
    "DEPARTAMENTO": "ADMINISTRAÇÃO",
    "OBS": ""
  }
];
