# src/analyzers/config.py
import re

DEFAULT_CONFIG = {
    # Deduplicação de pagamentos (janela em dias por tipo)
    "DEDUP_WINDOWS": {"PIX": 7, "TED": 7, "FATURA": 31, "DEFAULT": 30},
    "MEMO_SIM_DUPLICATE": 0.65,

    # Atipicidade (Z-score adaptativo)
    "ATYPICAL_ZSCORE":     2.0,
    "ATYPICAL_MIN_VALUE":  500.0,
    "ATYPICAL_MIN_SAMPLE": 5,

    "RETURN_WINDOW_DAYS":        10,
    "MAX_UNAPPLIED_WINDOW_DAYS": 5,

    "CASH_REMNANT_SURPLUS": 1500.0,
    "ROUND_AMOUNT_MIN":     1000.0,
    "ROUND_AMOUNT_STEP":     500.0,
    "ROUND_AMOUNT_WHITELIST_MEMO": re.compile(r"SALARIO|FOLHA|ALUGUEL|LOCACAO|CONTRATO|MENSALIDADE|SUBSIDIO|BOLSA|AUXILIO", re.IGNORECASE),

    "AFTER_HOURS_MIN_VALUE": 500.0,
    "AFTER_HOURS_START_HOUR": 7,
    "AFTER_HOURS_END_HOUR":  22,

    "FNAS_DIVERGENCE_PCT": 0.20,
    "FNAS_SEASONAL_MONTHS": {"12": 1.25, "01": 0.80},

    "SMURFING_MIN_ITEMS":     3,
    "SMURFING_WINDOW_DAYS":   7,
    "SMURFING_MIN_TOTAL":  8000.0,
    "SMURFING_CV_THRESHOLD":  0.05,
    "SMURFING_VELOCITY_COUNT": 5,
    "SMURFING_VELOCITY_DAYS":  3,

    "CREEP_MIN_MONTHS":  4,
    "CREEP_GROWTH_PCT":  0.30,
    "CREEP_MIN_AVG":   300.0,

    "BALANCE_TOLERANCE":    0.05,
    "BALANCE_MAX_GAP_DAYS": 5,

    "BENFORD_MIN_SAMPLE":     60,
    "BENFORD_CHI2_WARNING": 20.09,
    "BENFORD_CHI2_INFO":    15.51,

    "WEEKEND_MIN_VALUE": 500.0,

    "PROCUREMENT_THRESHOLDS": [8000.0, 17600.0, 59906.0],
    "PROCUREMENT_SKIRT_PCT":  0.03,

    "DORMANT_MIN_GAP_DAYS":   60,
    "DORMANT_BURST_DAYS":      7,
    "DORMANT_BURST_MIN_COUNT": 3,
    "DORMANT_BURST_MIN_TOTAL": 5000.0,

    "YEAR_END_MIN_MONTHS": 4,
    "YEAR_END_RATIO":      2.0,

    # Risk score
    "RISK_RECENT_WINDOW_DAYS":       60,
    "RISK_RECENT_BOOST":            1.2,
    "RISK_STALE_DISCOUNT":          0.8,
    "RISK_CONCENTRATION_MIN_ALERTS":  4,
    "RISK_CONCENTRATION_SHARE":     0.7,
    "RISK_CONCENTRATION_DISCOUNT":  0.7,
}
